-- CREATE TABLE IF NOT EXISTS Run (
--  id INT NOT NULL,
--  title
-- );
-- DROP TABLE IF EXISTS Run;

CREATE TABLE IF NOT EXISTS Run (
   id SERIAL PRIMARY KEY,
   title VARCHAR(250) NOT NULL,
   started_on TIMESTAMP NOT NULL,
   completed_on TIMESTAMP NOT NULL,
   miles INT NOT NULL,
   location VARCHAR(50) NOT NULL
);

